language: python
python:
  - "2.7"
# whitelist of git branches to build
branches:
  only:
    - master
# install required system packages
addons:
  apt:
    packages:
    - python-dev
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pyftpdlib pytest-xdist linkchecker
  - pip uninstall requests -y
  - pip install requests==2.4.0
# command to run tests
script: python linkchecker $site
# do not send emails of broken builds
notifications:
  email: true
